[
  {
    "author_association": "COLLABORATOR",
    "body": "It is \"by-design\" for cmdlets processing single file to write a terminating error.",
    "created_at": "2020-02-23T07:18:18Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-590034975",
    "id": 590034975,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDAzNDk3NQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590034975/reactions"
    },
    "updated_at": "2020-02-23T07:18:18Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590034975",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/22290914?v=4",
      "events_url": "https://api.github.com/users/iSazonov/events{/privacy}",
      "followers_url": "https://api.github.com/users/iSazonov/followers",
      "following_url": "https://api.github.com/users/iSazonov/following{/other_user}",
      "gists_url": "https://api.github.com/users/iSazonov/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/iSazonov",
      "id": 22290914,
      "login": "iSazonov",
      "node_id": "MDQ6VXNlcjIyMjkwOTE0",
      "organizations_url": "https://api.github.com/users/iSazonov/orgs",
      "received_events_url": "https://api.github.com/users/iSazonov/received_events",
      "repos_url": "https://api.github.com/users/iSazonov/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/iSazonov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iSazonov/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/iSazonov"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "@jasonmull, it sounds like your $ErrorPreference might be set differently between 5.1 and 7?\r\n\r\nYou might try deliberately specifying the error action of 'continue' with the Get-FileHash cmdlet. \r\n\r\nI don't think there is supposed to be any difference between 5.1 and 7 as long as all preferences are set the same.",
    "created_at": "2020-02-23T08:10:52Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-590038217",
    "id": 590038217,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDAzODIxNw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590038217/reactions"
    },
    "updated_at": "2020-02-23T08:10:52Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590038217",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/26179051?v=4",
      "events_url": "https://api.github.com/users/msftrncs/events{/privacy}",
      "followers_url": "https://api.github.com/users/msftrncs/followers",
      "following_url": "https://api.github.com/users/msftrncs/following{/other_user}",
      "gists_url": "https://api.github.com/users/msftrncs/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/msftrncs",
      "id": 26179051,
      "login": "msftrncs",
      "node_id": "MDQ6VXNlcjI2MTc5MDUx",
      "organizations_url": "https://api.github.com/users/msftrncs/orgs",
      "received_events_url": "https://api.github.com/users/msftrncs/received_events",
      "repos_url": "https://api.github.com/users/msftrncs/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/msftrncs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/msftrncs/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/msftrncs"
    }
  },
  {
    "author_association": "NONE",
    "body": "> It is \"by-design\" for cmdlets processing single file to write a terminating error.\r\n\r\nThis command is not processing a single file.  It is running against an entire directory.  In 7, it terminates on this file, but in 5.1, it errors and continues.\r\n\r\n> @jasonmull, it sounds like your $ErrorPreference might be set differently between 5.1 and 7?\r\n> \r\n> You might try deliberately specifying the error action of 'continue' with the Get-FileHash cmdlet.\r\n> \r\n> I don't think there is supposed to be any difference between 5.1 and 7 as long as all preferences are set the same.\r\n\r\nI've verified that $ErrorActionPreference is set to Continue in both instances and I've manually defined that action in the script.  No change.",
    "created_at": "2020-02-23T12:45:36Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-590065133",
    "id": 590065133,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDA2NTEzMw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590065133/reactions"
    },
    "updated_at": "2020-02-23T12:47:30Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590065133",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/4792624?v=4",
      "events_url": "https://api.github.com/users/jasonmull/events{/privacy}",
      "followers_url": "https://api.github.com/users/jasonmull/followers",
      "following_url": "https://api.github.com/users/jasonmull/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasonmull/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/jasonmull",
      "id": 4792624,
      "login": "jasonmull",
      "node_id": "MDQ6VXNlcjQ3OTI2MjQ=",
      "organizations_url": "https://api.github.com/users/jasonmull/orgs",
      "received_events_url": "https://api.github.com/users/jasonmull/received_events",
      "repos_url": "https://api.github.com/users/jasonmull/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/jasonmull/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasonmull/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/jasonmull"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "* In WinPS, `Get-FileHash` is a _function_ that caught _any_ exception in its `process` block and reported it as a _non-terminating_ error.\r\n\r\n* For PS Core, `Get-FileHash` was re-implemented as a _cmdlet_ (by @iSazonov, I believe :), and it currently catches only two specific exceptions, the one at hand _not_ being among them, which explains the effectively statement-terminating error (uncaught exception).\r\n\r\nhttps://github.com/PowerShell/PowerShell/blob/697dc5b37149d0dd98c34c33a87c833a23fe467e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs#L127-L163\r\n\r\nSounds like all that is needed is to add a catch-all `catch` branch.\r\n\r\n",
    "created_at": "2020-02-23T17:18:55Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-590092897",
    "id": 590092897,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDA5Mjg5Nw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590092897/reactions"
    },
    "updated_at": "2020-02-23T18:20:59Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590092897",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "PR is pulled but I don't know that causes the exception to add a test.",
    "created_at": "2020-02-24T18:45:14Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-590487273",
    "id": 590487273,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDQ4NzI3Mw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 1,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 1,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590487273/reactions"
    },
    "updated_at": "2020-02-24T18:45:14Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/590487273",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/22290914?v=4",
      "events_url": "https://api.github.com/users/iSazonov/events{/privacy}",
      "followers_url": "https://api.github.com/users/iSazonov/followers",
      "following_url": "https://api.github.com/users/iSazonov/following{/other_user}",
      "gists_url": "https://api.github.com/users/iSazonov/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/iSazonov",
      "id": 22290914,
      "login": "iSazonov",
      "node_id": "MDQ6VXNlcjIyMjkwOTE0",
      "organizations_url": "https://api.github.com/users/iSazonov/orgs",
      "received_events_url": "https://api.github.com/users/iSazonov/received_events",
      "repos_url": "https://api.github.com/users/iSazonov/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/iSazonov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iSazonov/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/iSazonov"
    }
  },
  {
    "author_association": "NONE",
    "body": ":tada:This issue was addressed in #11944, which has now been successfully released as `v7.1.0-preview.1`.:tada:\n\nHandy links:\n* [Release Notes](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.1)\n",
    "created_at": "2020-03-26T17:48:18Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11931#issuecomment-604578886",
    "id": 604578886,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11931",
    "node_id": "MDEyOklzc3VlQ29tbWVudDYwNDU3ODg4Ng==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/604578886/reactions"
    },
    "updated_at": "2020-03-26T17:48:18Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/604578886",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/in/26612?v=4",
      "events_url": "https://api.github.com/users/msftbot%5Bbot%5D/events{/privacy}",
      "followers_url": "https://api.github.com/users/msftbot%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/msftbot%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/msftbot%5Bbot%5D/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/apps/msftbot",
      "id": 48340428,
      "login": "msftbot[bot]",
      "node_id": "MDM6Qm90NDgzNDA0Mjg=",
      "organizations_url": "https://api.github.com/users/msftbot%5Bbot%5D/orgs",
      "received_events_url": "https://api.github.com/users/msftbot%5Bbot%5D/received_events",
      "repos_url": "https://api.github.com/users/msftbot%5Bbot%5D/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/msftbot%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/msftbot%5Bbot%5D/subscriptions",
      "type": "Bot",
      "url": "https://api.github.com/users/msftbot%5Bbot%5D"
    }
  }
]
