[
  {
    "author_association": "COLLABORATOR",
    "body": "This looks like the issue here isn't actually the suggestion being shown... Suggestions are shown if any errors show up in `$error`.\r\n\r\nI suspect the reason the error turns up is to do with how common parameters like -ErrorAction are handled when a command inside a module calls a command from another module. If I'm not mistaken, it might be a known issue that such parameters aren't always passed properly when calling commands in this way?\r\n\r\nDon't see the issue right now, but I'm sure I've seen it before somewhere...",
    "created_at": "2020-02-20T21:37:29Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11906#issuecomment-589330852",
    "id": 589330852,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11906",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU4OTMzMDg1Mg==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589330852/reactions"
    },
    "updated_at": "2020-02-20T21:37:29Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589330852",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Thanks vexx32.\r\n\r\n> Suggestions are shown if any errors show up in $error\r\n\r\nThat doesn't seem like the right way to do it. For example, if I instead use `-ErrorAction SilentlyContinue`, I **do** expect the error to go into `$error`, but *not* show up in output. And if the error is not showing up in output, then I don't know why we'd want to show the suggestion--there's no context for the user to understand why in the world this suggestion is being given.",
    "created_at": "2020-02-20T23:55:48Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11906#issuecomment-589429903",
    "id": 589429903,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11906",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU4OTQyOTkwMw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589429903/reactions"
    },
    "updated_at": "2020-02-20T23:55:48Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589429903",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/771085?v=4",
      "events_url": "https://api.github.com/users/jazzdelightsme/events{/privacy}",
      "followers_url": "https://api.github.com/users/jazzdelightsme/followers",
      "following_url": "https://api.github.com/users/jazzdelightsme/following{/other_user}",
      "gists_url": "https://api.github.com/users/jazzdelightsme/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/jazzdelightsme",
      "id": 771085,
      "login": "jazzdelightsme",
      "node_id": "MDQ6VXNlcjc3MTA4NQ==",
      "organizations_url": "https://api.github.com/users/jazzdelightsme/orgs",
      "received_events_url": "https://api.github.com/users/jazzdelightsme/received_events",
      "repos_url": "https://api.github.com/users/jazzdelightsme/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/jazzdelightsme/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jazzdelightsme/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/jazzdelightsme"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "Yep, I'd definitely agree. ðŸ™‚ \r\n\r\nI have a WIP PR #9115 that addresses that by adding a Suggestion property onto the ErrorRecord itself and having the suggestion be shown as part of the error message formatting itself. I've not had time to finish it, but @SteveL-MSFT has expressed interest in continuing that work. ",
    "created_at": "2020-02-21T00:03:56Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11906#issuecomment-589432780",
    "id": 589432780,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11906",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU4OTQzMjc4MA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 1,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 1,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589432780/reactions"
    },
    "updated_at": "2020-02-21T00:03:56Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/589432780",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  }
]
