[
  {
    "author_association": "MEMBER",
    "body": "The whole terminating vs non-terminating errors consistently is misunderstood.  Even in some of our product code I see these mistakes and I make them myself.  Perhaps an option here is to add HadTerminatingErrors, while HadErrors continues to capture Terminating/Nonterminating (even if handled/suppressed)?",
    "created_at": "2017-08-31T03:40:30Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-326180770",
    "id": 326180770,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyNjE4MDc3MA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326180770/reactions"
    },
    "updated_at": "2017-08-31T03:40:30Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326180770",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "I agree discussion is required because error handling in PowerShell is a point of confusion. This particular issue has nothing to do with terminating vs non-terminating though. This has to do with handled vs non-handled, which is a completely different thing.\r\n\r\nIf I invoke a .NET method that internally receives some exception but handles that exception gracefully and then eventually returns back to me without error, should $? return $true or $false? The answer in that case is quite clear: it should return $true because there was no error as far as I, the method invoker, am concerned.\r\n\r\nI believe PowerShell command invocations should behave no differently. In both examples I shared above, I am instructing PowerShell to suppress the error if one occurs. In other words, the error is handled in my command. Yet S.M.A.PowerShell.HadErrors returns $true and $? returns $false.\r\n\r\nAside -- This related behaviour also surprises me. Try executing these commands one at a time.\r\n```PowerShell\r\nGet-Service -Name Invalid\r\n$? # returns $false\r\nGet-Service -Name Invalid -ErrorAction Stop\r\n$? # returns $false\r\ntry {Get-Service -Name Invalid -ErrorAction Stop} catch {<# Ignore the error, it's benign #>}\r\n$? # returns $false -- shouldn't this return $true?\r\n& {try {Get-Service -Name Invalid -ErrorAction Stop} catch {<# Ignore the error, it's benign #>}}\r\n$? # returns $true\r\n```",
    "created_at": "2017-08-31T16:05:37Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-326344277",
    "id": 326344277,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyNjM0NDI3Nw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326344277/reactions"
    },
    "updated_at": "2017-08-31T16:05:37Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326344277",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/3515485?v=4",
      "events_url": "https://api.github.com/users/KirkMunro/events{/privacy}",
      "followers_url": "https://api.github.com/users/KirkMunro/followers",
      "following_url": "https://api.github.com/users/KirkMunro/following{/other_user}",
      "gists_url": "https://api.github.com/users/KirkMunro/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/KirkMunro",
      "id": 3515485,
      "login": "KirkMunro",
      "node_id": "MDQ6VXNlcjM1MTU0ODU=",
      "organizations_url": "https://api.github.com/users/KirkMunro/orgs",
      "received_events_url": "https://api.github.com/users/KirkMunro/received_events",
      "repos_url": "https://api.github.com/users/KirkMunro/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/KirkMunro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/KirkMunro/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/KirkMunro"
    }
  },
  {
    "author_association": "MEMBER",
    "body": "I see.  I think that `HadErrors` and `$?` should be consistent in that they are only true if there are unhandled errors, but will defer to @PowerShell/powershell-committee to understand the history and original intent.",
    "created_at": "2017-08-31T19:16:10Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-326394423",
    "id": 326394423,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyNjM5NDQyMw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326394423/reactions"
    },
    "updated_at": "2017-08-31T19:16:10Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/326394423",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "MEMBER",
    "body": "@PowerShell/powershell-committee reviewed this\r\n\r\n```powershell\r\n(get-service -name invalid); $?\r\nTrue\r\nget-service -name invalid; $?\r\nFalse\r\n```\r\nthe two above statements should be equivalent, however, it's not.  The bug seems to be that in @KirkMunro 's samples above, #3 should return $true and the two equivalent statements here should both return $false.",
    "created_at": "2017-09-06T23:24:00Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-327638891",
    "id": 327638891,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyNzYzODg5MQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/327638891/reactions"
    },
    "updated_at": "2017-09-06T23:24:00Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/327638891",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "@SteveL-MSFT:\r\n\r\nThe reason that `(get-service -name invalid); $?` returns true is the previously discussed issue that `(...)` turns a command into an _expression_ and it is then (unexpectedly) the _expression_'s success that determines the value of `$?`, and the mere act of enclosing a command in `(...)` is a \"successful\" expression - see [Automatic $? variable is reset to $True when a command is enclosed in parentheses - make $? only reflect command status, not expression status\r\n](https://github.com/PowerShell/PowerShell/issues/3359)\r\n\r\n@KirkMunro:\r\n\r\nRe `try {Get-Service -Name Invalid -ErrorAction Stop} catch {<# Ignore the error, it's benign #>}` returning `$False`:\r\n\r\nTo recap from https://github.com/PowerShell/PowerShell/issues/3768#issuecomment-323405734:\r\n> checking `$?` after `try` / `catch` is virtually pointless, because what `$?` is set to depends on whether the catch block happens to be empty (`$False`) or not (whatever statement happens to execute _last_ in the catch block determines the value of `$?`).\r\n\r\nSimilarly (unexpectedly), _anything_ that you invoke via `& { ... }` - i.e., `&` with a _script block_ - currently makes `$?` indicate `$True`; try `& { nosuchcommand }; $?` and `& { 1 / 0 }; $?`\r\n\r\n\r\n\r\n\r\n",
    "created_at": "2017-09-12T22:36:43Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-329003774",
    "id": 329003774,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyOTAwMzc3NA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/329003774/reactions"
    },
    "updated_at": "2017-09-12T22:36:43Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/329003774",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "MEMBER",
    "body": "Re-reviewing issues @PowerShell/powershell-committee had reviewed prior to GA to see if the decision would still stand post GA.\r\n\r\nFor this issue, based on @mklement0's explanation, it seems this is working as designed and I think just needs to be documented appropriately.",
    "created_at": "2018-03-16T21:18:59Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-373847853",
    "id": 373847853,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3Mzg0Nzg1Mw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373847853/reactions"
    },
    "updated_at": "2018-03-16T21:18:59Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373847853",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "@SteveL-MSFT I strongly disagree. Suggesting sample 1 from the original post is by design is wrong.\r\n\r\nYou tell PowerShell to outright _ignore errors_ in part of an invocation you make from C#, and then PowerShell says oh, hey, there were errors, so you check, but there weren't any, PowerShell lied.\r\n\r\n**This completely breaks any trust that a developer can have in HadErrors, and forces them to wrap the invocation of PowerShell and build their own HadErrors because HadErrors is broken.**\r\n\r\nYou can't document \"broken\" appropriately.",
    "created_at": "2018-03-16T22:10:19Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-373858549",
    "id": 373858549,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3Mzg1ODU0OQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373858549/reactions"
    },
    "updated_at": "2018-03-16T22:13:18Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373858549",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/3515485?v=4",
      "events_url": "https://api.github.com/users/KirkMunro/events{/privacy}",
      "followers_url": "https://api.github.com/users/KirkMunro/followers",
      "following_url": "https://api.github.com/users/KirkMunro/following{/other_user}",
      "gists_url": "https://api.github.com/users/KirkMunro/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/KirkMunro",
      "id": 3515485,
      "login": "KirkMunro",
      "node_id": "MDQ6VXNlcjM1MTU0ODU=",
      "organizations_url": "https://api.github.com/users/KirkMunro/orgs",
      "received_events_url": "https://api.github.com/users/KirkMunro/received_events",
      "repos_url": "https://api.github.com/users/KirkMunro/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/KirkMunro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/KirkMunro/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/KirkMunro"
    }
  },
  {
    "author_association": "MEMBER",
    "body": "@KirkMunro sorry, I focused only on the last few replies.  Looking at your original sample, I would tend to agree that if you handle the error (or suppress it by choice), `.HadErrors` shouldn't indicate an error occurred.  Remarked for @PowerShell/powershell-committee review to understand the history/intent.",
    "created_at": "2018-03-16T23:56:49Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-373874985",
    "id": 373874985,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3Mzg3NDk4NQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373874985/reactions"
    },
    "updated_at": "2018-03-16T23:56:49Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/373874985",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "MEMBER",
    "body": "@PowerShell/powershell-committee reviewed this:\r\n\r\n- `.HadErrors` was originally designed for use with PSWorkflow.  Recommendation is to remove this property or at least mark as deprecated, because PSWorkflow is not in PSCore6.   If there is a need for `.HadErrors` equivalent, recommendation is to have a proposal for a new property to fill this need.\r\n- Regarding `$?`, the intent should be that if there are not any errors written to `$error`, then `$?` is `$true`, else it's `$false`.\r\n- These changes should be posted as an RFC.",
    "created_at": "2018-03-21T23:02:02Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-375123996",
    "id": 375123996,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NTEyMzk5Ng==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/375123996/reactions"
    },
    "updated_at": "2018-03-21T23:02:02Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/375123996",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11859881?v=4",
      "events_url": "https://api.github.com/users/SteveL-MSFT/events{/privacy}",
      "followers_url": "https://api.github.com/users/SteveL-MSFT/followers",
      "following_url": "https://api.github.com/users/SteveL-MSFT/following{/other_user}",
      "gists_url": "https://api.github.com/users/SteveL-MSFT/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SteveL-MSFT",
      "id": 11859881,
      "login": "SteveL-MSFT",
      "node_id": "MDQ6VXNlcjExODU5ODgx",
      "organizations_url": "https://api.github.com/users/SteveL-MSFT/orgs",
      "received_events_url": "https://api.github.com/users/SteveL-MSFT/received_events",
      "repos_url": "https://api.github.com/users/SteveL-MSFT/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SteveL-MSFT/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SteveL-MSFT/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SteveL-MSFT"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "> Regarding $?, the intent should be that if there are not any errors written to $error, then $? is $true, else it's $false.\r\n\r\n@SteveL-MSFT This statement is not quite right. I think you meant \"written to the error stream\" not \"written to $error\". That said, the following code\r\n```\r\nget-item nosuchitem 2> $null ; $?\r\n```\r\n**MUST** return false. The _$? variable is the only way for a script to determine that a command failed_ and take action (without adding the complexity of exceptions). For example:\r\n```\r\n$content = get-content foo.txt 2> $null\r\nif ($?) \r\n{ \r\n    \"Do stuff with content\" \r\n} \r\nelse { \r\n    \"Handle error\" \r\n}\r\n```\r\nLike any shell, the value of $? is only valid right after the command or expression you are interested in has executed. If you need to use it after doing a bunch of other stuff, save it in another variable. If you are executing the command in another scope, don't expect that $? in your scope will be affected.\r\n\r\nOne important thing that is missing is a way for functions and scriptblocks to indicate to the caller that they failed. (Scripts can do it by calling exit 1). \r\n",
    "created_at": "2018-03-24T00:08:44Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-375829312",
    "id": 375829312,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NTgyOTMxMg==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/375829312/reactions"
    },
    "updated_at": "2018-03-24T00:08:44Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/375829312",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/6876108?v=4",
      "events_url": "https://api.github.com/users/BrucePay/events{/privacy}",
      "followers_url": "https://api.github.com/users/BrucePay/followers",
      "following_url": "https://api.github.com/users/BrucePay/following{/other_user}",
      "gists_url": "https://api.github.com/users/BrucePay/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/BrucePay",
      "id": 6876108,
      "login": "BrucePay",
      "node_id": "MDQ6VXNlcjY4NzYxMDg=",
      "organizations_url": "https://api.github.com/users/BrucePay/orgs",
      "received_events_url": "https://api.github.com/users/BrucePay/received_events",
      "repos_url": "https://api.github.com/users/BrucePay/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/BrucePay/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BrucePay/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/BrucePay"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "A few tangents:\r\n\r\n> I think you meant \"written to the error stream\" not \"written to $error\".\r\n\r\nTrue, but as an aside: `2> $null` still causes errors to be logged in `$Error`, perhaps surprisingly (as such it is the equivalent of `-ErrorAction SilentlyContinue`); only `-ErrorAction Ignore` prevents that.\r\n\r\n> The $? variable is the only way for a script to determine that a command failed and take action (without adding the complexity of exceptions).\r\n\r\nThat makes sense, but given how easy it is to wipe out the last command's `$?` status (e.g., statements such as `(get-content nosuchfile) -match 'hi'` and `@(get-content nosuchfile)`, ... making `$?` return `$True`), `$?` is currently of limited value - see https://github.com/PowerShell/PowerShell/issues/3359#issuecomment-287842045\r\n\r\n> One important thing that is missing is a way for functions and scriptblocks to indicate to the caller that they failed. (Scripts can do it by calling exit 1).\r\n\r\nWhile an explicit way to do that would definitely be nice, making `Write-Error` calls set `$?` in the _caller's_ scope would go a long way - see #3629",
    "created_at": "2018-03-26T15:08:55Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-376200133",
    "id": 376200133,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NjIwMDEzMw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/376200133/reactions"
    },
    "updated_at": "2018-04-21T13:07:47Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/376200133",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Someone just hit the `$?`-is-still-`$false`-with-`-ErrorAction Ignore` issue indirectly [on Stack Overflow](https://stackoverflow.com/q/55459737/45375), in the context of a Makefile:\r\n\r\nA recipe such as `powershell -c \" Remove-Item -ErrorAction Ignore file.txt\"` unexpectedly fails if an error was ignored, because `$?` is mapped onto exit codes `0` and `1`.\r\n",
    "created_at": "2019-04-03T12:15:05Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-479463697",
    "id": 479463697,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTQ2MzY5Nw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479463697/reactions"
    },
    "updated_at": "2019-04-03T12:15:05Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479463697",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "I think perhaps this might be resolved by splitting the functionality expected from `$?`\r\n\r\nCurrently it reports a mixed status, depending on the last executed command OR expression. And, as far as I can think this morning, the only way an _expression_ would fail is if it's pretty much nonsensical and is either a parse or something like a math error, using operators in a context they don't allow, e.g., `\"hello\" % 2`\r\n\r\nWhat if we split this in two, so that we have a variable like `$LastCmdletFailed` and a `$LastExpressionFailed` ?",
    "created_at": "2019-04-03T12:23:13Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-479466235",
    "id": 479466235,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTQ2NjIzNQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479466235/reactions"
    },
    "updated_at": "2019-04-03T12:23:13Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479466235",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Agreed that `$?` shouldn't report virtually-always-successful expression status, @vexx32, and this has come up before in #3359, which asks that `$?`:\r\n\r\n* only ever reflect the last _command_'s status \r\n* including whether the previous statement (whether command or expression) was aborted due to a _statement-terminating error_ - which is what `\"hello\" % 2` triggers (more simply `1 / 0`).\r\n\r\nIn other words: if an expression (or command) was aborted due to a statement-terminating error, `$?` is sensibly `$false`, but it never makes sense for a \"successful\" (i.e., non-aborted) expression to set `$?` to `$true`, as is currently the case.\r\n\r\nWith that, I'd say there's no need for a separate `$LastExpressionFailed`.",
    "created_at": "2019-04-03T12:38:29Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-479471060",
    "id": 479471060,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTQ3MTA2MA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 1,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 1,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479471060/reactions"
    },
    "updated_at": "2019-04-03T12:39:56Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479471060",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "That certainly seems to be pretty sensible to me. I can't really think of a case that doesn't effectively cover. 😄 ",
    "created_at": "2019-04-03T12:49:52Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-479474813",
    "id": 479474813,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTQ3NDgxMw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 1,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 1,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479474813/reactions"
    },
    "updated_at": "2019-04-03T12:49:52Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/479474813",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "> only ever reflect the last command's status\r\n\r\nI'd amend the quoted statement, as follows:\r\n\r\n\"only ever reflect the status of the last command that was executed _in the current scope_\".\r\n\r\nI've never, ever wanted it to work differently, and could care less about the status of the last command that was invoked any number of levels deep inside of something I invoked.",
    "created_at": "2019-04-10T15:21:41Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-481736371",
    "id": 481736371,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MTczNjM3MQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481736371/reactions"
    },
    "updated_at": "2019-04-10T15:22:34Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481736371",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/3515485?v=4",
      "events_url": "https://api.github.com/users/KirkMunro/events{/privacy}",
      "followers_url": "https://api.github.com/users/KirkMunro/followers",
      "following_url": "https://api.github.com/users/KirkMunro/following{/other_user}",
      "gists_url": "https://api.github.com/users/KirkMunro/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/KirkMunro",
      "id": 3515485,
      "login": "KirkMunro",
      "node_id": "MDQ6VXNlcjM1MTU0ODU=",
      "organizations_url": "https://api.github.com/users/KirkMunro/orgs",
      "received_events_url": "https://api.github.com/users/KirkMunro/received_events",
      "repos_url": "https://api.github.com/users/KirkMunro/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/KirkMunro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/KirkMunro/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/KirkMunro"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "Definitely agreed on that. If my function handles an error state but doesn't itself emit an error, that error should not magically show up in $error or $?.",
    "created_at": "2019-04-10T15:30:06Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-481739930",
    "id": 481739930,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MTczOTkzMA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481739930/reactions"
    },
    "updated_at": "2019-04-10T15:30:06Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481739930",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Agreed.\r\n\r\n* Fortunately, at least in PowerShell code it already seems to work that way:\r\n\r\n```powershell\r\n & { gci /nosuch }; $?  # $True - fortunately, the gci status did NOT leak\r\n```\r\n\r\n* Unfortunately, you can't set the `$?` status for your caller from PowerShell code - see #3629\r\n\r\n```powershell\r\n & { Write-Error 'oh no' }; $?  # !! $True - despite the use of Write-Error\r\n```\r\nThe workaround is to use `$PSCmdlet.WriteError()`, but that's (a) cumbersome and (b) only available in _advanced_ function/scripts.\r\n\r\n\r\n",
    "created_at": "2019-04-10T16:55:10Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/4613#issuecomment-481773518",
    "id": 481773518,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/4613",
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MTc3MzUxOA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481773518/reactions"
    },
    "updated_at": "2019-04-10T16:55:10Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/481773518",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  }
]
