[
  {
    "author_association": "COLLABORATOR",
    "body": "ðŸ¤” One would think it should be caught, since it does appear to be a terminating error; it is caught with `try`/`catch`.\r\n\r\nThis looks like it might be intentional, at least in part; if a user defines a `trap{}` in their profile script, for example, it would make it exceedingly difficult to see when they get a command not found error at the command line, if the trap was catching that error.",
    "created_at": "2020-01-23T13:48:23Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577688785",
    "id": 577688785,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11665",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU3NzY4ODc4NQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577688785/reactions"
    },
    "updated_at": "2020-01-23T13:48:34Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577688785",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/32407840?v=4",
      "events_url": "https://api.github.com/users/vexx32/events{/privacy}",
      "followers_url": "https://api.github.com/users/vexx32/followers",
      "following_url": "https://api.github.com/users/vexx32/following{/other_user}",
      "gists_url": "https://api.github.com/users/vexx32/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vexx32",
      "id": 32407840,
      "login": "vexx32",
      "node_id": "MDQ6VXNlcjMyNDA3ODQw",
      "organizations_url": "https://api.github.com/users/vexx32/orgs",
      "received_events_url": "https://api.github.com/users/vexx32/received_events",
      "repos_url": "https://api.github.com/users/vexx32/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vexx32/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vexx32/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vexx32"
    }
  },
  {
    "author_association": "COLLABORATOR",
    "body": "I think that doc just needs to be fixed.  `trap` doesn't silence errors unless you include `continue`.\r\n\r\n```powershell\r\nfunction TrapTest {\r\n    trap {\r\n        \"Error found.\"\r\n        continue\r\n    }\r\n\r\n    nonsenseString\r\n}\r\n\r\nTrapTest\r\n# Error found.\r\n```\r\n\r\n@vexx32 \r\n\r\n> This looks like it might be intentional, at least in part; if a user defines a `trap{}` in their profile script, for example, it would make it exceedingly difficult to see when they get a command not found error at the command line, if the trap was catching that error.\r\n\r\nOnly for the profile itself.  Traps propagate to child scopes, but cannot be dot sourced:\r\n\r\n```powershell\r\n. { trap { 'something'; continue } }\r\nthrow\r\n# Throws normally\r\n```",
    "created_at": "2020-01-23T18:35:07Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577814339",
    "id": 577814339,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11665",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU3NzgxNDMzOQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 2,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 2,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577814339/reactions"
    },
    "updated_at": "2020-01-23T18:35:07Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577814339",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/24977523?v=4",
      "events_url": "https://api.github.com/users/SeeminglyScience/events{/privacy}",
      "followers_url": "https://api.github.com/users/SeeminglyScience/followers",
      "following_url": "https://api.github.com/users/SeeminglyScience/following{/other_user}",
      "gists_url": "https://api.github.com/users/SeeminglyScience/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/SeeminglyScience",
      "id": 24977523,
      "login": "SeeminglyScience",
      "node_id": "MDQ6VXNlcjI0OTc3NTIz",
      "organizations_url": "https://api.github.com/users/SeeminglyScience/orgs",
      "received_events_url": "https://api.github.com/users/SeeminglyScience/received_events",
      "repos_url": "https://api.github.com/users/SeeminglyScience/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/SeeminglyScience/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SeeminglyScience/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/SeeminglyScience"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Actually, it _is_ caught (note that `Error is found` prints), it just doesn't _suppress the error message_.\r\n\r\nCurrently, `trap` forces you to choose between:\r\n\r\n* _displaying_ the error (_after_ processing the `trap` script block)  and _continuing_ execution (default behavior, without a flow-control statement in the `trap` script block)\r\n\r\n* _displaying_ the error and _aborting_ execution (with `break` in the script block)\r\n\r\n* _silencing_ the error, but _continuing_ execution (with `continue` in the script block)\r\n\r\nIf you want to _both_ silence and abort, the only thing that gets you _close_ to is to use `exit` or `return` in the script block, but that doesn't guarantee that processing aborts _overall_.\r\n\r\nA few sample commands to illustrate the behaviors:\r\n\r\n```powershell\r\n& { trap { \"Error found.\" } 1/0; 'ok' }; 'after'\r\n\r\n& { trap { \"Error found.\"; continue } 1/0; 'ok' }; 'after'\r\n\r\n& { trap { \"Error found.\"; break } 1/0; 'ok' }; 'after'\r\n\r\n& { trap { \"Error found.\"; return } 1/0; 'ok' }; 'after'\r\n```\r\n",
    "created_at": "2020-01-23T22:57:03Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577916683",
    "id": 577916683,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11665",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU3NzkxNjY4Mw==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577916683/reactions"
    },
    "updated_at": "2020-01-23T22:57:03Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577916683",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "Oops, @SeeminglyScience - wires crossed, but I hope my comment is still useful.",
    "created_at": "2020-01-23T22:58:10Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577916988",
    "id": 577916988,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11665",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU3NzkxNjk4OA==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 1,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 1,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577916988/reactions"
    },
    "updated_at": "2020-01-23T22:58:10Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577916988",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  },
  {
    "author_association": "CONTRIBUTOR",
    "body": "I've asked for the docs to be amended: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5348\r\n\r\n@he852100, I think it's fine to close this issue now.",
    "created_at": "2020-01-23T23:44:01Z",
    "html_url": "https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577930035",
    "id": 577930035,
    "issue_url": "https://api.github.com/repos/PowerShell/PowerShell/issues/11665",
    "node_id": "MDEyOklzc3VlQ29tbWVudDU3NzkzMDAzNQ==",
    "performed_via_github_app": null,
    "reactions": {
      "+1": 0,
      "-1": 0,
      "confused": 0,
      "eyes": 0,
      "heart": 0,
      "hooray": 0,
      "laugh": 0,
      "rocket": 0,
      "total_count": 0,
      "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577930035/reactions"
    },
    "updated_at": "2020-01-23T23:44:01Z",
    "url": "https://api.github.com/repos/PowerShell/PowerShell/issues/comments/577930035",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/588825?v=4",
      "events_url": "https://api.github.com/users/mklement0/events{/privacy}",
      "followers_url": "https://api.github.com/users/mklement0/followers",
      "following_url": "https://api.github.com/users/mklement0/following{/other_user}",
      "gists_url": "https://api.github.com/users/mklement0/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mklement0",
      "id": 588825,
      "login": "mklement0",
      "node_id": "MDQ6VXNlcjU4ODgyNQ==",
      "organizations_url": "https://api.github.com/users/mklement0/orgs",
      "received_events_url": "https://api.github.com/users/mklement0/received_events",
      "repos_url": "https://api.github.com/users/mklement0/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mklement0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mklement0/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mklement0"
    }
  }
]
