{
  "_url": "https://github.com/PowerShell/PowerShell/issues/11036",
  "author": "thboop",
  "body": "It appears that commands that redirect std-err (such as `npm ping`) called consecutively in a script that does not open in a new window causes powershell to exit with code 1, rather then execute the commands and exit with code 0.\r\n\r\nI've linked a quick project showing this [problem](https://github.com/thboop/PowerShell-Repro)\r\n\r\n# Steps to reproduce\r\nSee\r\nhttps://github.com/thboop/PowerShell-Repro/blob/master/test/Program.cs#L11\r\n\r\n``` C#\r\n            var command = \"'\" + Directory.GetCurrentDirectory().Replace(@\"\\\\\", @\"\\\") + @\"\\test.ps1'\"\"\";\r\n            var _proc = new Process();\r\n            // REPLACE WITH DIRECTORY OF YOUR PWSH\r\n            _proc.StartInfo.FileName = @\"C:\\Program Files\\PowerShell\\6\\pwsh.EXE\";\r\n            var arguement = @\"-command \"\". \" + command;\r\n            _proc.StartInfo.Arguments = arguement;\r\n            _proc.StartInfo.UseShellExecute = false;\r\n            _proc.StartInfo.RedirectStandardInput = true;\r\n            _proc.StartInfo.RedirectStandardError = true;\r\n            _proc.StartInfo.RedirectStandardOutput = true;\r\n            \r\n            // ******************************************************************\r\n            // Setting this line to true causes powershell core to exit code 1\r\n            _proc.StartInfo.CreateNoWindow = true; \r\n            // ******************************************************************\r\n\r\n            var response = _proc.Start();\r\n            _proc.WaitForExit();\r\n            Console.WriteLine(_proc.StandardOutput.ReadToEnd());\r\n            Console.WriteLine(_proc.StandardError.ReadToEnd());\r\n            Console.WriteLine($\"exited with exit code {_proc.ExitCode}\");\r\n```\r\n\r\nShell Script it invokes\r\n```\r\n$ErrorActionPreference = 'stop'\r\n\r\nnpm ping\r\nnpm ping\r\nnpm ping\r\n```\r\n\r\n# Expected behavior\r\n\r\n```none\r\nPowershell Exits with Code 0 and runs the commands\r\n```\r\n\r\n# Actual behavior\r\n\r\n```none\r\nPowershell exits with code 1\r\n```\r\n\r\n# Environment data\r\n\r\n```none\r\nPSVersion                      6.2.3\r\nPSEdition                      Core\r\nGitCommitId                    6.2.3\r\nOS                             Microsoft Windows 10.0.17763\r\nPlatform                       Win32NT\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u2026}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\r\n\r\nnode -v\r\nv10.16.0\r\n```\r\n",
  "closed_at": "2020-04-14T15:26:30Z",
  "comments": [
    {
      "author": "rjmholt",
      "author_association": "COLLABORATOR",
      "body": "I'm unable to reproduce this on my machine:\r\n\r\n```\r\n> .\\bin\\Debug\\netcoreapp3.0\\publish\\testexe.exe\r\n\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.217ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.189ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.302ms\r\n\r\nexited with exit code 0\r\n```\r\n\r\n```\r\n> dotnet run\r\n\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.188ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.192ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.535ms\r\n\r\nexited with exit code 0\r\n```\r\n\r\nTried it with both 6.2.3 and 7.0.0-preview.5.\r\n\r\nMy platform:\r\n\r\n```\r\nName                           Value\r\n----                           -----\r\nPSVersion                      7.0.0-preview.5\r\nPSEdition                      Core\r\nGitCommitId                    7.0.0-preview.5\r\nOS                             Microsoft Windows 10.0.19013\r\nPlatform                       Win32NT\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u0393\u00c7\u00aa}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\r\n```\r\n\r\nAny further details about when PowerShell exits or any other error messages logged or shown?\r\n\r\n<blockquote></blockquote>",
      "created_at": "2019-11-12T01:06:41Z",
      "updated_at": "2019-11-12T01:07:06Z"
    },
    {
      "author": "thboop",
      "author_association": "NONE",
      "body": "@rjmholt Thanks for looking into this!\r\n\r\nI'm able to confirm that `7.0.0-preview 5` is working correctly, but `powershell 6` is not.\r\n\r\nI recompiled in .net core 3.0 to match your build\r\nPowershell 6\r\n```\r\nPS PowerShell-Exit\\bin\\Debug\\netcoreapp3.0> .\\PowerShell-Exit.exe\r\n\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.353ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.336ms\r\nnpm notice PING https://registry.npmjs.org/\r\n\r\nexited with exit code 1\r\n```\r\n\r\nNotice how we don't receive output from the last npm ping\r\n\r\n\r\nPowershell 7.0.0-preview5\r\n`_proc.StartInfo.FileName = @\"C:\\Program Files\\PowerShell\\7-preview\\pwsh.EXE\";`\r\n\r\n```\r\nPS C:\\Users\\thboop\\source\\repos\\PowerShell-Exit\\PowerShell-Exit\\bin\\Debug\\netcoreapp3.0> .\\PowerShell-Exit.exe\r\n\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.518ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.396ms\r\nnpm notice PING https://registry.npmjs.org/\r\nnpm notice PONG 0.402ms\r\n\r\nexited with exit code 0\r\n```\r\n\r\nCould there be a conditional environment option causing this on powershell 6? Is there any more information I can provide from my environment? We are seeing this on more then just one machine.\r\n\r\nI'm very glad to see Powershell 7 is working!\r\n",
      "created_at": "2019-11-12T18:49:11Z",
      "updated_at": "2019-11-12T18:58:49Z"
    },
    {
      "author": "thboop",
      "author_association": "NONE",
      "body": "Resolved in powershell 7",
      "created_at": "2020-04-14T15:26:30Z",
      "updated_at": "2020-04-14T15:26:30Z"
    }
  ],
  "created_at": "2019-11-11T19:27:18Z",
  "labels": [
    "Issue-Question"
  ],
  "number": 11036,
  "state": "closed",
  "title": "Powershell Script in same shell exits with error code 1 on certain commands",
  "updated_at": "2020-04-14T15:26:31Z"
}