{
  "_url": "https://github.com/PowerShell/PowerShell/issues/1528",
  "author": "PaulHigin",
  "body": "When establishing a connection for an SSH remote session, if a transport error occurs during Runspace.Open(), that error is ignored and the client waits until a one minute connection time out occurs.  PowerShell throws an \"SSH.exe process not created\" exception but this exception doesn't get propagated and the connection attempt wait continues until connection timeout occurs.\n## Steps to reproduce\n1.  Set up SSH based remoting on a Windows machine (see docs)\n2.  Try to create a session using an invalid user or host name.\n   $session = New-PSSession -HostName <BadName> -UserName <username>\n## Expected behavior\n\nWhen ssh.exe fails to make the connection PowerShell should propagate the exception and quit New-PSSession while displaying the error.\n## Actual behavior\n\nPowerShell New-PSSession Cmdlet appears to continue waiting for a connection (or appears hung) until the one minute connection timeout occurs that finally allows New-PSSession to quit with error.\n## Environment data\n\nName                           Value\n\n---\n\nPSVersion                      5.1.10032.0\nPSEdition                      WindowsPowerShell\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}\nBuildVersion                   3.0.0.0\nGitCommitId                    v0.6.0-376-g87ae333f7d3c7727c60369f086aa3dfe9a6bc176-dirty\nCLRVersion                     4.0.30319.42000\nWSManStackVersion              3.0\nPSRemotingProtocolVersion      2.3\nSerializationVersion           1.1.0.1\n",
  "closed_at": "2016-08-19T14:48:59Z",
  "comments": [
    {
      "author": "PaulHigin",
      "author_association": "COLLABORATOR",
      "body": "Fixed with PR #1856\n",
      "created_at": "2016-08-19T14:48:59Z",
      "updated_at": "2016-09-15T18:14:34Z"
    }
  ],
  "created_at": "2016-07-26T22:55:40Z",
  "labels": [
    "Resolution-Fixed"
  ],
  "number": 1528,
  "state": "closed",
  "title": "SSH based remoting does not handle errors during connection attempt",
  "updated_at": "2016-09-15T18:14:50Z"
}