{
  "_url": "https://github.com/PowerShell/PowerShell/issues/16684",
  "author": "anttiah",
  "body": "### Prerequisites\n\n- [X] Write a descriptive title.\n- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)\n- [X] Search the existing issues.\n- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).\n- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).\n\n### Steps to reproduce\n\nRemoting cmdlets that support the SSHConnection hash table parameter fail to create session if in the hash table:\r\n`KeyFilePath` is specified using tilde syntax, e.g. `~/.ssh/id_myidentity` instead of full path of the file.\r\nor\r\n`ConnectingTimeout` is not specified.\r\n\r\nSteps to reproduce using tilde syntax in the `KeyFilePath`, regardless of `ConnectingTimeout` existence or value:\r\n```\r\nPS /home/user> New-PSSession -SSHConnection @{\r\n    HostName    = 'x.x.x.x'\r\n    Port        = yyyyy\r\n    UserName    = 'administrator'\r\n    KeyFilePath = '~/.ssh/id_myidentity'\r\n}\r\nNew-PSSession: [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.\r\n```\r\n\r\nSteps to reproduce using full path syntax in the `KeyFilePath` and without specifying `ConnectingTimeout`:\r\n```\r\nPS /home/user> New-PSSession -SSHConnection @{\r\n    HostName    = 'x.x.x.x'\r\n    Port        = yyyyy\r\n    UserName    = 'administrator'\r\n    KeyFilePath = '/home/user/.ssh/id_myidentity'\r\n}\r\nNew-PSSession: [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.\r\n```\r\n\r\nCommand works only when using both full path syntax in the `KeyFilePath` and `ConnectingTimeout` value of `-1` (or something large enough): \r\n```\r\nPS /home/user> New-PSSession -SSHConnection @{\r\n    HostName          = 'x.x.x.x'\r\n    Port              = yyyyy\r\n    UserName          = 'administrator'\r\n    KeyFilePath       = '/home/user/.ssh/id_myidentity'\r\n    ConnectingTimeout = -1\r\n}\r\n Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability\r\n -- ----            --------- ------------    ------------    -----         -----------------     ------------\r\n 39 Runspace38      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available\r\n```\r\n\r\nSplatting the hash table also seem to work regardless of the `KeyFilePath` syntax or `ConnectingTimeout` value:\r\n```\r\nPS /home/user1> $sshparams = @{\r\n    HostName    = 'x.x.x.x'\r\n    Port        = yyyyy\r\n    UserName    = 'administrator'\r\n    KeyFilePath = '~/.ssh/id_myidentity'\r\n}\r\nPS /home/user1> New-PSSession @sshparams\r\n\r\n Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability\r\n -- ----            --------- ------------    ------------    -----         -----------------     ------------\r\n 47 Runspace46      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available\r\n```\r\n\r\n\n\n### Expected behavior\n\n```console\nConnection succeeds with KeyFilePath tilde syntax and without specifying ConnectingTimeout.\n```\n\n\n### Actual behavior\n\n```console\nNew-PSSession: [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.\r\n\r\n# Or\r\n\r\nNew-PSSession: [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.\n```\n\n\n### Error details\n\n```console\n###############################################################################\r\n# Error when using tilde syntax in the KeyFilePath, regardless of ConnectingTimeout existence or value:\r\n\r\nException             :\r\n    Type           : System.Management.Automation.Remoting.PSRemotingDataStructureException\r\n    ErrorRecord    :\r\n        Exception             :\r\n            Type    : System.Management.Automation.ParentContainsErrorRecordException\r\n            Message : An error has occurred which PowerShell cannot handle. A remote session might have ended.\r\n            HResult : -2146233087\r\n        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException\r\n        FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException\r\n    Message        : An error has occurred which PowerShell cannot handle. A remote session might have ended.\r\n    InnerException :\r\n        Type       : System.IO.FileNotFoundException\r\n        Message    : The specified key file ~/.ssh/id_myidentity was not found.\r\n        TargetSite :\r\n            Name          : StartSSHProcess\r\n            DeclaringType : System.Management.Automation.Runspaces.SSHConnectionInfo\r\n            MemberType    : Method\r\n            Module        : System.Management.Automation.dll\r\n        Source     : System.Management.Automation\r\n        HResult    : -2147024894\r\n        StackTrace :\r\n   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)\r\n   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()\r\n   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)\r\n   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)\r\n   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()\r\n   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()\r\n    HResult        : -2146233087\r\nTargetObject          : System.Management.Automation.RemoteRunspace\r\nCategoryInfo          : OpenError: (System.Management.A\u2026tion.RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingDataStructureException\r\nFullyQualifiedErrorId : PSSessionOpenFailed\r\nErrorDetails          : [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.\r\nInvocationInfo        :\r\n    MyCommand        : New-PSSession\r\n    ScriptLineNumber : 1\r\n    OffsetInLine     : 1\r\n    HistoryId        : 61\r\n    Line             : New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyy; UserName = 'administrator'; KeyFilePath =\r\n'~/.ssh/id_myidentity'; ConnectingTimeout = -1}\r\n    PositionMessage  : At line:1 char:1\r\n                       + New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yy \u2026\r\n                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    InvocationName   : New-PSSession\r\n    CommandOrigin    : Internal\r\nScriptStackTrace      : at <ScriptBlock>, <No file>: line 1\r\nPipelineIterationInfo :\r\n\r\n\r\n\r\n###############################################################################\r\n# Error when using full path syntax in the KeyFilePath and without specifying ConnectingTimeout:\r\n\r\nException             :\r\n    Type        : System.Management.Automation.Remoting.PSRemotingTransportException\r\n    ErrorRecord :\r\n        Exception             :\r\n            Type    : System.Management.Automation.ParentContainsErrorRecordException\r\n            Message : SSH connection attempt failed after time out: 0 seconds.\r\n            HResult : -2146233087\r\n        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException\r\n        FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException\r\n    Message     : SSH connection attempt failed after time out: 0 seconds.\r\n    HResult     : -2146233087\r\nTargetObject          : System.Management.Automation.RemoteRunspace\r\nCategoryInfo          : OpenError: (System.Management.A\u2026tion.RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException\r\nFullyQualifiedErrorId : PSSessionOpenFailed\r\nErrorDetails          : [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.\r\nInvocationInfo        :\r\n    MyCommand        : New-PSSession\r\n    ScriptLineNumber : 1\r\n    OffsetInLine     : 1\r\n    HistoryId        : 63\r\n    Line             : New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath =\r\n'/home/user/.ssh/id_myidentity'}\r\n    PositionMessage  : At line:1 char:1\r\n                       + New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yy \u2026\r\n                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    InvocationName   : New-PSSession\r\n    CommandOrigin    : Internal\r\nScriptStackTrace      : at <ScriptBlock>, <No file>: line 1\r\nPipelineIterationInfo :\n```\n\n\n### Environment data\n\n```powershell\nName                           Value\r\n----                           -----\r\nPSVersion                      7.2.1\r\nPSEdition                      Core\r\nGitCommitId                    7.2.1\r\nOS                             Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29)\r\nPlatform                       Unix\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u2026}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\n```\n\n\n### Visuals\n\n_No response_",
  "closed_at": null,
  "comments": [
    {
      "author": "kasini3000",
      "author_association": "NONE",
      "body": "```\r\nGet-Content -ReadCount 0 @{\r\n\tLiteralPath = 'd:\\h.txt'\r\n} # error\r\nGet-Content -ReadCount 0 -LiteralPath 'd:\\h.txt' #normal\r\n\r\nGet-FileHash -Algorithm sha1 @{\r\n\tLiteralPath = 'd:\\h.txt'\r\n} #error\r\nGet-FileHash -Algorithm sha1 -LiteralPath 'd:\\h.txt' #normal\r\n```\r\n**Obviously, the powershell parsing engine is not designed in the way you understand the grammar.**\r\nYou should not expect powershell to parse the \r\n```\r\n~\r\n``` \r\nin the string. If you want to do this, use Resolve-Path,eg: \r\nKeyFilePath = Resolve-Path -path '~/.ssh/id_myidentity'",
      "created_at": "2022-01-01T17:41:51Z",
      "updated_at": "2022-01-01T17:43:45Z"
    },
    {
      "author": "anttiah",
      "author_association": "NONE",
      "body": "Just noticed that result depens on the order the hash table keys are processed.\r\nUnordered hash table fails because `Port` is not handled correctly:\r\n```\r\nNew-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath = '/home/user/.ssh/id_myidentity'; ConnectingTimeout = -1}\r\nNew-PSSession: [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to host x.x.x.x port 22: Connection timed out.\r\n```\r\n\r\nWhile ordered works:\r\n```\r\nNew-PSSession -SSHConnection ([ordered]@{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath = '/home/user/.ssh/id_myidentity'; ConnectingTimeout = -1})\r\n\r\n Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability\r\n -- ----            --------- ------------    ------------    -----         -----------------     ------------\r\n 77 Runspace76      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available\r\n```\r\n\r\nNo wonder this was so hard to investigate. Root cause has probably been around for a while because this is not the first bug report on the `-SSHConnection` hash table.\r\n\r\n**EDIT:**\r\nI'm getting inconsistent results on repeated tests with indentical commands when I log off and logon between attemps. Sometimes the `Port` key doesn't have effect, then on next attempt the `KeyFilePath` might fail etc.\r\n\r\nBut every now and then the command just works. There is something weird going on with the internal state of the PowerShell.",
      "created_at": "2022-01-03T10:23:08Z",
      "updated_at": "2022-01-03T15:01:53Z"
    },
    {
      "author": "anttiah",
      "author_association": "NONE",
      "body": "Ok, did more tests and there is definitely something wrong with how the hash table is processed.\r\n\r\nThis is my test setup. First I created a simple PowerShell script:\r\n```\r\n# sessiontest.ps1\r\nNew-PSSession -SSHConnection @{\r\n    Port              = 2222\r\n    UserName          = 'administrator'\r\n    HostName          = 'x.x.x.x'\r\n    KeyFilePath       = '/home/user/.ssh/id_myidentity'\r\n    ConnectingTimeout = 30000    # 30 seconds\r\n} -PipelineVariable session | Write-Verbose -Message {\"We got session $_\"} -Verbose | Remove-PSSession -Session {$session}\r\n```\r\nThen I ran the script 10 times from Bash command line:\r\n`for i in {1..10}; do echo \"Loop ${i}:\"; pwsh -file ~/sessiontest.ps1; done`\r\n\r\n**Expected result**\r\n`New-PSSession` command succeeds every time.\r\n```\r\nLoop 1:\r\nVERBOSE: We got session [PSSession]Runspace1\r\n...\r\nLoop 10:\r\nVERBOSE: We got session [PSSession]Runspace1\r\n```\r\n\r\n**Actual result**\r\n`New-PSSession` command fails randomly. Based on the error message some of the hash table keys had no effect or got replaced with default value. In this sample, only loop 3 successfully connected, while loops 1,2,4,5,6,7,8,10 failed due to wrong port, and loop 9 failed due to wrong identity. Repeated executions of the bash command gave similar results but with different loops failing every time.\r\n```\r\nLoop 1:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 2:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 3:\r\nVERBOSE: We got session [PSSession]Runspace1\r\nLoop 4:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 5:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 6:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 7:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 8:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n\r\nLoop 9:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message:\r\n     | user@x.x.x.x: Permission denied (publickey)..\r\n\r\nLoop 10:\r\nNew-PSSession: /home/user/sessiontest.ps1:1\r\nLine |\r\n   1 |  New-PSSession -SSHConnection @{\r\n     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to\r\n     | host x.x.x.x port 22: Connection timed out.\r\n```\r\nFinally, I ran the same setup from my WSL2 Ubuntu w/ PowerShell 7.2.1 against another server and results were just as random as with the original system.\r\n",
      "created_at": "2022-01-03T16:30:50Z",
      "updated_at": "2022-01-03T16:30:50Z"
    },
    {
      "author": "E3V3A",
      "author_association": "NONE",
      "body": "Looks to me like the `Port = 2222` is ignored. \r\nAlternatively I suggest you to change the port for each connection, or restart your sshd after each connection, or close the connection, depending on how many sessions you allow in your sshd. Also put a 3 sec sleep in your loop. ",
      "created_at": "2022-01-31T22:00:18Z",
      "updated_at": "2022-01-31T22:02:55Z"
    },
    {
      "author": "anttiah",
      "author_association": "NONE",
      "body": "> Looks to me like the `Port = 2222` is ignored. Alternatively I suggest you to change the port for each connection, or restart your sshd after each connection, or close the connection, depending on how many sessions you allow in your sshd. Also put a 3 sec sleep in your loop.\r\n\r\nAs you can see from my previous comment, https://github.com/PowerShell/PowerShell/issues/16684#issuecomment-1004209585, failure is random. Based on my small sample, it seems to be weighted towards `Port` being ignored but there is also one failure caused by ignored `KeyFilePath`.\r\n\r\nThe test was run from outside `pwsh` using `bash`'s loop syntax. Thus, new `pwsh` process was started for each iteration and exited immediately after. The PowerShell portion of the test also removed each successfull connection before exiting.\r\n\r\nThe server I'm testing this on can handle 100+ outbound ssh connections without issues. I've ran lots of PowerShell commands against large groups of servers simultaneously using splatting syntax with the same hash table and it works just fine.\r\n\r\nAnd let's not forget the timeout issue. In the hash table the `ConnectingTimeout` must be explicitly defined to be non-zero or the connection will fail immediately due to default timeout being 0 milliseconds.",
      "created_at": "2022-02-01T06:38:02Z",
      "updated_at": "2022-02-01T06:38:02Z"
    },
    {
      "author": "E3V3A",
      "author_association": "NONE",
      "body": "What if you use: \r\n`for i in {1..10}; do echo \"Loop ${i}:\"; $(pwsh -nop -nol -file ~/sessiontest.ps1); sleep 2; done`",
      "created_at": "2022-02-01T13:37:11Z",
      "updated_at": "2022-02-01T13:37:11Z"
    },
    {
      "author": "anttiah",
      "author_association": "NONE",
      "body": "If it were about concurrent ssh sessions, then the first iteration should succeed. But it doesn't. It fails randomly. Please note that the bash loop in my example is for demonstration purposes only. I originally discovered this issue when trying to manage multiple servers (one ssh connection per server) and the `New-PSSession -SSHConnection $arrayofhashtables` command kept failing while the same commad with splatting syntax never failed even when there were dozens of active connections.",
      "created_at": "2022-02-01T14:02:03Z",
      "updated_at": "2022-02-01T14:02:03Z"
    },
    {
      "author": "PaulHigin",
      "author_association": "COLLABORATOR",
      "body": "@WG-Remoting\r\nRemoting working group agrees that the KeyFilePath parameter should try PowerShell path resolution before throwing the 'not found' error.  ",
      "created_at": "2022-04-07T17:43:39Z",
      "updated_at": "2022-04-07T17:43:39Z"
    }
  ],
  "created_at": "2021-12-31T15:20:13Z",
  "labels": [
    "Issue-Bug",
    "WG-Remoting"
  ],
  "number": 16684,
  "state": "open",
  "title": "Remoting over SSH: Multiple issues with the SSHConnection parameter",
  "updated_at": "2022-04-07T17:43:51Z"
}